import type { LanguageOption, DonationToken } from '@/types'

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
]

export const CREATOR_WALLET = '0xde760afc274878cc6710c438376432a0c68d0037'
export const CREATOR_FID = 250704
export const CREATOR_USERNAME = 'ukhy89'

export const DONATION_TOKENS: DonationToken[] = [
  { symbol: 'ETH', decimals: 18 },
  { symbol: 'USDC', address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', decimals: 6 },
]

export const BASE_CHAIN_ID = 8453

// Comprehensive gesture phrases in multiple languages (40+ phrases)
export const GESTURE_PHRASES: Record<string, Record<string, string>> = {
  // Basic Greetings
  hello: {
    en: 'Hello',
    id: 'Halo',
    zh: '你好',
    ru: 'Привет',
    ar: 'مرحبا',
    th: 'สวัสดี',
    vi: 'Xin chào',
  },
  goodbye: {
    en: 'Goodbye',
    id: 'Selamat tinggal',
    zh: '再见',
    ru: 'До свидания',
    ar: 'وداعا',
    th: 'ลาก่อน',
    vi: 'Tạm biệt',
  },
  goodmorning: {
    en: 'Good morning',
    id: 'Selamat pagi',
    zh: '早上好',
    ru: 'Доброе утро',
    ar: 'صباح الخير',
    th: 'สวัสดีตอนเช้า',
    vi: 'Chào buổi sáng',
  },
  goodnight: {
    en: 'Good night',
    id: 'Selamat malam',
    zh: '晚安',
    ru: 'Спокойной ночи',
    ar: 'تصبح على خير',
    th: 'ราตรีสวัสดิ์',
    vi: 'Chúc ngủ ngon',
  },
  howareyou: {
    en: 'How are you?',
    id: 'Apa kabar?',
    zh: '你好吗？',
    ru: 'Как дела?',
    ar: 'كيف حالك؟',
    th: 'สบายดีไหม?',
    vi: 'Bạn khỏe không?',
  },
  nice: {
    en: 'Nice to meet you',
    id: 'Senang bertemu Anda',
    zh: '很高兴见到你',
    ru: 'Приятно познакомиться',
    ar: 'سعيد بلقائك',
    th: 'ยินดีที่ได้รู้จัก',
    vi: 'Rất vui được gặp bạn',
  },
  
  // Polite Expressions
  thankyou: {
    en: 'Thank you',
    id: 'Terima kasih',
    zh: '谢谢',
    ru: 'Спасибо',
    ar: 'شكرا',
    th: 'ขอบคุณ',
    vi: 'Cảm ơn',
  },
  thankyouverymuch: {
    en: 'Thank you very much',
    id: 'Terima kasih banyak',
    zh: '非常感谢',
    ru: 'Большое спасибо',
    ar: 'شكرا جزيلا',
    th: 'ขอบคุณมาก',
    vi: 'Cảm ơn rất nhiều',
  },
  please: {
    en: 'Please',
    id: 'Tolong',
    zh: '请',
    ru: 'Пожалуйста',
    ar: 'من فضلك',
    th: 'กรุณา',
    vi: 'Làm ơn',
  },
  sorry: {
    en: 'Sorry',
    id: 'Maaf',
    zh: '对不起',
    ru: 'Извините',
    ar: 'آسف',
    th: 'ขอโทษ',
    vi: 'Xin lỗi',
  },
  excuseme: {
    en: 'Excuse me',
    id: 'Permisi',
    zh: '打扰一下',
    ru: 'Извините',
    ar: 'عفوا',
    th: 'ขอโทษ',
    vi: 'Xin lỗi',
  },
  youarewelcome: {
    en: 'You are welcome',
    id: 'Sama-sama',
    zh: '不客气',
    ru: 'Пожалуйста',
    ar: 'على الرحب',
    th: 'ไม่เป็นไร',
    vi: 'Không có gì',
  },
  
  // Agreement & Understanding
  yes: {
    en: 'Yes',
    id: 'Ya',
    zh: '是',
    ru: 'Да',
    ar: 'نعم',
    th: 'ใช่',
    vi: 'Vâng',
  },
  no: {
    en: 'No',
    id: 'Tidak',
    zh: '不',
    ru: 'Нет',
    ar: 'لا',
    th: 'ไม่',
    vi: 'Không',
  },
  understand: {
    en: 'I understand',
    id: 'Saya mengerti',
    zh: '我明白',
    ru: 'Я понимаю',
    ar: 'أفهم',
    th: 'ฉันเข้าใจ',
    vi: 'Tôi hiểu',
  },
  notunderstand: {
    en: "I don't understand",
    id: 'Saya tidak mengerti',
    zh: '我不明白',
    ru: 'Я не понимаю',
    ar: 'لا أفهم',
    th: 'ฉันไม่เข้าใจ',
    vi: 'Tôi không hiểu',
  },
  agree: {
    en: 'I agree',
    id: 'Saya setuju',
    zh: '我同意',
    ru: 'Я согласен',
    ar: 'أوافق',
    th: 'ฉันเห็นด้วย',
    vi: 'Tôi đồng ý',
  },
  maybe: {
    en: 'Maybe',
    id: 'Mungkin',
    zh: '也许',
    ru: 'Может быть',
    ar: 'ربما',
    th: 'อาจจะ',
    vi: 'Có thể',
  },
  
  // Requests & Needs
  help: {
    en: 'Help me please',
    id: 'Tolong bantu saya',
    zh: '请帮帮我',
    ru: 'Помогите мне пожалуйста',
    ar: 'ساعدني من فضلك',
    th: 'ช่วยฉันด้วย',
    vi: 'Xin hãy giúp tôi',
  },
  wait: {
    en: 'Please wait',
    id: 'Mohon tunggu',
    zh: '请等一下',
    ru: 'Подождите пожалуйста',
    ar: 'انتظر من فضلك',
    th: 'โปรดรอสักครู่',
    vi: 'Vui lòng đợi',
  },
  repeat: {
    en: 'Please repeat',
    id: 'Mohon ulangi',
    zh: '请再说一遍',
    ru: 'Повторите пожалуйста',
    ar: 'كرر من فضلك',
    th: 'กรุณาพูดอีกครั้ง',
    vi: 'Xin hãy lặp lại',
  },
  slowly: {
    en: 'Please speak slowly',
    id: 'Mohon bicara pelan-pelan',
    zh: '请慢慢说',
    ru: 'Говорите медленнее пожалуйста',
    ar: 'تحدث ببطء من فضلك',
    th: 'กรุณาพูดช้าๆ',
    vi: 'Xin hãy nói chậm',
  },
  water: {
    en: 'I need water',
    id: 'Saya butuh air',
    zh: '我需要水',
    ru: 'Мне нужна вода',
    ar: 'أحتاج إلى ماء',
    th: 'ฉันต้องการน้ำ',
    vi: 'Tôi cần nước',
  },
  bathroom: {
    en: 'Where is the bathroom?',
    id: 'Di mana kamar mandi?',
    zh: '洗手间在哪里？',
    ru: 'Где туалет?',
    ar: 'أين الحمام؟',
    th: 'ห้องน้ำอยู่ที่ไหน?',
    vi: 'Nhà vệ sinh ở đâu?',
  },
  
  // Emotions & States
  happy: {
    en: 'I am happy',
    id: 'Saya senang',
    zh: '我很高兴',
    ru: 'Я счастлив',
    ar: 'أنا سعيد',
    th: 'ฉันมีความสุข',
    vi: 'Tôi vui',
  },
  sad: {
    en: 'I am sad',
    id: 'Saya sedih',
    zh: '我很难过',
    ru: 'Мне грустно',
    ar: 'أنا حزين',
    th: 'ฉันเศร้า',
    vi: 'Tôi buồn',
  },
  tired: {
    en: 'I am tired',
    id: 'Saya lelah',
    zh: '我累了',
    ru: 'Я устал',
    ar: 'أنا متعب',
    th: 'ฉันเหนื่อย',
    vi: 'Tôi mệt',
  },
  sick: {
    en: 'I am sick',
    id: 'Saya sakit',
    zh: '我病了',
    ru: 'Я болен',
    ar: 'أنا مريض',
    th: 'ฉันป่วย',
    vi: 'Tôi bị ốm',
  },
  hungry: {
    en: 'I am hungry',
    id: 'Saya lapar',
    zh: '我饿了',
    ru: 'Я голоден',
    ar: 'أنا جائع',
    th: 'ฉันหิว',
    vi: 'Tôi đói',
  },
  
  // Places & Directions
  home: {
    en: 'I want to go home',
    id: 'Saya ingin pulang',
    zh: '我想回家',
    ru: 'Я хочу домой',
    ar: 'أريد أن أذهب إلى المنزل',
    th: 'ฉันอยากกลับบ้าน',
    vi: 'Tôi muốn về nhà',
  },
  hospital: {
    en: 'Take me to the hospital',
    id: 'Antar saya ke rumah sakit',
    zh: '带我去医院',
    ru: 'Отвезите меня в больницу',
    ar: 'خذني إلى المستشفى',
    th: 'พาฉันไปโรงพยาบาล',
    vi: 'Đưa tôi đến bệnh viện',
  },
  left: {
    en: 'Turn left',
    id: 'Belok kiri',
    zh: '向左转',
    ru: 'Поверните налево',
    ar: 'انعطف يسارا',
    th: 'เลี้ยวซ้าย',
    vi: 'Rẽ trái',
  },
  right: {
    en: 'Turn right',
    id: 'Belok kanan',
    zh: '向右转',
    ru: 'Поверните направо',
    ar: 'انعطف يمينا',
    th: 'เลี้ยวขวา',
    vi: 'Rẽ phải',
  },
  stop: {
    en: 'Stop',
    id: 'Berhenti',
    zh: '停',
    ru: 'Стоп',
    ar: 'توقف',
    th: 'หยุด',
    vi: 'Dừng lại',
  },
  
  // Emergency & Important
  emergency: {
    en: 'This is an emergency!',
    id: 'Ini darurat!',
    zh: '这是紧急情况！',
    ru: 'Это чрезвычайная ситуация!',
    ar: 'هذه حالة طارئة!',
    th: 'นี่คือเหตุฉุกเฉิน!',
    vi: 'Đây là tình huống khẩn cấp!',
  },
  danger: {
    en: 'Danger!',
    id: 'Bahaya!',
    zh: '危险！',
    ru: 'Опасность!',
    ar: 'خطر!',
    th: 'อันตราย!',
    vi: 'Nguy hiểm!',
  },
  callpolice: {
    en: 'Call the police',
    id: 'Panggil polisi',
    zh: '叫警察',
    ru: 'Вызовите полицию',
    ar: 'اتصل بالشرطة',
    th: 'โทรหาตำรวจ',
    vi: 'Gọi cảnh sát',
  },
  
  // Daily Life
  eat: {
    en: 'Let\'s eat',
    id: 'Mari makan',
    zh: '我们吃饭吧',
    ru: 'Давайте поедим',
    ar: 'دعونا نأكل',
    th: 'มากินกันเถอะ',
    vi: 'Chúng ta ăn thôi',
  },
  drink: {
    en: 'I want to drink',
    id: 'Saya ingin minum',
    zh: '我想喝水',
    ru: 'Я хочу пить',
    ar: 'أريد أن أشرب',
    th: 'ฉันอยากดื่ม',
    vi: 'Tôi muốn uống',
  },
  sleep: {
    en: 'I want to sleep',
    id: 'Saya ingin tidur',
    zh: '我想睡觉',
    ru: 'Я хочу спать',
    ar: 'أريد أن أنام',
    th: 'ฉันอยากนอน',
    vi: 'Tôi muốn ngủ',
  },
  beautiful: {
    en: 'Beautiful',
    id: 'Cantik',
    zh: '美丽',
    ru: 'Красиво',
    ar: 'جميل',
    th: 'สวย',
    vi: 'Đẹp',
  },
  love: {
    en: 'I love you',
    id: 'Aku cinta kamu',
    zh: '我爱你',
    ru: 'Я люблю тебя',
    ar: 'أحبك',
    th: 'ฉันรักคุณ',
    vi: 'Anh yêu em',
  },
  friend: {
    en: 'You are my friend',
    id: 'Kamu adalah temanku',
    zh: '你是我的朋友',
    ru: 'Ты мой друг',
    ar: 'أنت صديقي',
    th: 'คุณเป็นเพื่อนของฉัน',
    vi: 'Bạn là bạn của tôi',
  },
}
